[2022-10-01 18:17:23,565] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:17:23,596] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:17:23,598] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:17:23,602] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-01 18:17:23,607] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:17:23,669] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cleaned_data_message> on 2022-10-01 18:11:09.504243+00:00
[2022-10-01 18:17:23,693] {standard_task_runner.py:52} INFO - Started process 2125 to run task
[2022-10-01 18:17:23,710] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_dag', 'cleaned_data_message', 'manual__2022-10-01T18:11:09.504243+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_dag/data_cleaning.py', '--cfg-path', '/tmp/tmpltwls3ef', '--error-file', '/tmp/tmpmxs69b_b']
[2022-10-01 18:17:23,714] {standard_task_runner.py:80} INFO - Job 11: Subtask cleaned_data_message
[2022-10-01 18:17:23,922] {task_command.py:371} INFO - Running <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [running]> on host 408deac6c455
[2022-10-01 18:17:24,061] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_cleaning_dag
AIRFLOW_CTX_TASK_ID=cleaned_data_message
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T18:11:09.504243+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T18:11:09.504243+00:00
[2022-10-01 18:17:24,063] {logging_mixin.py:115} INFO - Data successfully cleaned
[2022-10-01 18:17:24,064] {python.py:173} INFO - Done. Returned value was: None
[2022-10-01 18:17:24,088] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=data_cleaning_dag, task_id=cleaned_data_message, execution_date=20221001T181109, start_date=20221001T181723, end_date=20221001T181724
[2022-10-01 18:17:24,158] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 18:17:24,237] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
